### PR TITLE
Linked list (Singly & doubly) in C++

### PR DESCRIPTION
**Pull request by dushivani**

### CODE REVIEW

**Review by AjaySharvesh3 — CHANGES_REQUESTED** [review]
Just make it as a One folder of your files and then make PR. Like LinkedListC++ inside that make your files as Doubly and Singly Linked list

**Comment by dushivani** [comment]
Should I merge .cpp and .h files to one file or they can be placed in folder like singly (singly->singly.cpp singly.h) and doubly?

**Comment by dushivani** [comment]
Done. Please check.

**Review by AjaySharvesh3 — APPROVED** [review]
Now it's okay. PR Accepted.

**Pull request merged**
